spring.application.name=gateway-service
server.port=8080
logging.level.root=INFO

spring.config.import=optional:configserver:http://localhost:8888

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

resilience4j.circuitbreaker.instances.ecomBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.ecomBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.ecomBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.ecomBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.ecomBreaker.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.ecomBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.ecomBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.productService.slideWindowType= count_based