spring.application.name=configserver
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///C:/IntelliJCode/ecom-microservices/configserver/src/main/resources/config
server.port=8888
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5673
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.cloud.stream.bindings.springCloudBusInput.group=${spring.application.name}
#spring.datasource.rabbitmq.host=localhost
#spring.datasource.rabbitmq.port=5673
#spring.datasource.rabbitmq.username=guest
#spring.datasource.rabbitmq.password=guest
management.endpoints.web.exposure.include=*

